### ISSUE TITLE
Should probably keep a reference to wrapped runner, not base

### ISSUE THREAD

**Issue by longouyang** [probmods/webppl-editor#47]
Reproducing a Slack conversation:

**andreas**: on recent dev, we've changed how the trampolineRunner can be accessed (because we needed it for the mongodb params store and the old way would have made accessing it there complicated): https://github.com/probmods/webppl/blob/7df4adce7e057b34a2e634f2af1a27a042e51ad0/src/main.js#L231 — i think this means that the editor needs to adapt as well. can you take a look? i think it might be a very small change. if it looks like a bigger deal, let me know

**long**: i suspect that this doesn't matter. but for a somewhat bad reason. the editor creates a base runner and passes that into prepare. and then editor keeps a reference to the base runner around for things like resuming trampolining. i think that what the editor should do is keep a reference to the *wrapped* runner. in which case the recent access changes would matter. and i'm surprised that keeping only a ref to the base runner hasn't surfaced more errors

**Comment by null-a** [comment]
I think references to both the [base runner](https://github.com/probmods/webppl-editor/blob/master/src/index.js#L542) and the [wrapped runner](https://github.com/probmods/webppl-editor/blob/master/src/index.js#L543) are kept around.

The base runner is used to cancel the execution of programs. That this has to be done using the base runner makes sense to me, because the wrapped runner doesn't expose `__cancel__`.

The wrapped runner is stashed into a global variable and is used to resume execution after doing async. stuff. The next release of webppl will no longer return this wrapped runner from `prepare`, but will instead stash it in a global variable itself. (Using the same name as the editor. probmods/webppl#771.) I think this means a small change will be required to the editor to support the next release of webppl. The change will simple remove the editor code that stashes the wrapper runner in the global variable. (Since all this will do is clobber the reference stashed by webppl.) I'll open a PR to this effect shortly.

**Comment by longouyang** [comment]
> I think references to both the base runner and the wrapped runner are kept around.
> 
> The base runner is used to cancel the execution of programs. That this has to be done using the base runner makes sense to me, because the wrapped runner doesn't expose __cancel__.

Ah - you're right.
