### ISSUE TITLE
Provide a way for users to stop long-running computations

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl-editor#7]

**Comment by longouyang** [comment]
How does this sound?

Right before the model starts running, we add a cancel button -- when clicked, it sets the global variable `__trampoline_canceled__` to true. And we rewrite the web trampoline runner to check for this variable, halting if it's defined.

**Comment by stuhlmueller** [comment]
Good, apart from the fact that (as always) it would be better if we didn't need a global variable. Maybe the web trampoline runner could return a reference to an object `var obj = { 'stop': false }` and at each iteration check whether `obj.stop` is still false, stopping otherwise.

**Comment by longouyang** [comment]
I'm not sure that the current setup allows the trampoline runner to "return" anything.

To get your approach to work, I think we'd have to do something more complicated like:

`webppl.compile`, instead of returning a string, returns a _control object_:

``` js
{
  stopTrampoline: false,
  code: ...,
  otherMetadataWeWant: ...
}
```

The consumer of webppl can run code by `eval`ing the `code` property but it can also mutate/inspect other properties of the control object (in this case, we wire the cancel button to `stopTrampoline`). And we rewrite the web trampoline runner to check the control object.

**Comment by longouyang** [comment]
(Maybe the approach outlined is what you meant but I wanted to clarify on paper that you want to pass the control object at compile time -- trampoline time is too late [and harder to write, I think])

**Comment by stuhlmueller** [comment]
I don't think compile is the right place for this. Whether to stop or not is a property of a particular program execution and not a fact associated with the code. I'd refactor the trampoline driver (so that the expression constructed by the trampolining transform evaluates to a function that takes the control object as an argument) and `webppl.run` (so that it passes the control object to this function), but I'm not sure it's worth it. This would introduce additional complexity as well. Maybe we should go with the global variable for now.

**Comment by longouyang** [comment]
I think the control object -- in some form or another -- might be worth it, as we could also use it to expose the trampoline runner associated with a particular piece of code, as we discussed in probmods/webppl#291

**Comment by longouyang** [comment]
Never mind, there's not a single notion of control object that solves both these issues.

As discussed in this thread, it _might_ be worth it to pass an object to the trampoline runner to cancel long running jobs.

A separate idea is that `webppl.compile` should return an object with `code` and `runner` properties so that 3rd party libraries can call the appropriate runner for a piece of code without knowing details.

**Comment by longouyang** [comment]
I got this working in dccd3f8, though this relies on [run-time trampoline selection in webppl ](https://github.com/probmods/webppl/pull/291#issuecomment-180128500), which is not yet merged.

Note that this only works during execution, which runs with the pausy trampoline. Compilations runs without trampolining at all, so I think the GUI is locked up during this time.

**Comment by longouyang** [comment]
Runtime trampoline selection got merged so I can close this issue.
